POST http://localhost:8080/items
Content-Type: application/json

{
  "name": "onion",
  "unitMeasuredIn": "cups",
  "caloriesPerUnit": 50,
  "unitsAvailable": 3
}

###
POST http://localhost:8080/items
Content-Type: application/json

{
  "name": "garlic",
  "unitMeasuredIn": "grams",
  "caloriesPerUnit": 1,
  "unitsAvailable": 75
}

###
PUT http://localhost:8080/items/2
Content-Type: application/json

{
  "name": "garlic",
  "id": 2,
  "unitMeasuredIn": "grams",
  "caloriesPerUnit": 1,
  "unitsAvailable": 100
}

###

PUT http://localhost:8080/items/recipe/19999
Accept: application/json
###